version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # ★★★ 修正点: volumesを復活させ、コードの変更が即時反映されるようにする ★★★
    volumes:
      - ./frontend:/app
      # node_modulesはコンテナ内のものを使う、というおまじない
      - /app/node_modules
    command: sleep infinity
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      # ポート3001の衝突を避けるため、3002番を外部に公開する
      - "3002:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sleep infinity
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb?schema=public

  db:
    image: postgres:15
    container_name: callstatus_app_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: